CREATE TABLE [theRock].[Requests] (
    [requestId]                     INT            IDENTITY (1, 1) NOT NULL,
    [originFacilityCode]            NVARCHAR (50)  NULL,
    [referralNumber]                NVARCHAR (50)  NULL,
    [forwardCaseNumber]             NVARCHAR (50)  NULL,
    [paperFormId]                   NVARCHAR (50)  NULL,
    [referringDoctorName]           NVARCHAR (255) NULL,
    [nationalIdNumber]              NVARCHAR (50)  NULL,
    [patientGender]                 NVARCHAR (10)  NULL,
    [visibleDisability]             BIT            NULL,
    [phoneNumber]                   NVARCHAR (50)  NULL,
    [contactName]                   NVARCHAR (50)  NULL,
    [governorate]                   NVARCHAR (50)  NULL,
    [district]                      NVARCHAR (50)  NULL,
    [subdistrict]                   NVARCHAR (50)  NULL,
    [community]                     NVARCHAR (50)  NULL,
    [residentialStatus]             NVARCHAR (50)  NULL,
    [dateOfBirth]                   DATE           NULL,
    [age]                           INT            NULL,
    [ageUnit]                       NVARCHAR (10)  NULL,
    [isUrgent]                      BIT            NULL,
    [referralReason]                NVARCHAR (255) NULL,
    [forwardDiagnosis]              NVARCHAR (255) NULL,
    [forwardDiagnosisICD10]         NVARCHAR (255) NULL,
    [otherDiagnosisSupport]         NVARCHAR (255) NULL,
    [otherMedicalDevice]            NVARCHAR (255) NULL,
    [otherTreatmentOption]          NVARCHAR (255) NULL,
    [medicalHistory]                NVARCHAR (MAX) NULL,
    [clinicalAndMedicalExamination] NVARCHAR (MAX) NULL,
    [treatmentProvided]             NVARCHAR (MAX) NULL,
    [recommendations]               NVARCHAR (MAX) NULL,
    [height]                        INT            NULL,
    [weight]                        INT            NULL,
    [bloodPressure]                 NVARCHAR (50)  NULL,
    [oxygen]                        INT            NULL,
    [heartRate]                     INT            NULL,
    [temperatureInCelsius]          DECIMAL (5, 2) NULL,
    [status]                        NVARCHAR (50)  NULL,
    [createdAt]                     DATETIME       NULL,
    [updatedAt]                     DATETIME       NULL,
    [roundedCreatedDate]            DATETIME       NULL,
    [backformStatus]                NVARCHAR (50)  NULL,
    [destinationFacilityCode]       NVARCHAR (50)  NULL,
    [requestStatus]                 NVARCHAR (50)  NULL,
    [requestCreatedAt]              DATETIME       NULL,
    [referralStatus]                NVARCHAR (50)  NULL,
    [requestUpdatedAt]              DATETIME       NULL,
    CONSTRAINT [PK__Requests__E3C5DE3161BBC771] PRIMARY KEY CLUSTERED ([requestId] ASC)
);