CREATE   VIEW [theRock].[vwBackform]
AS
SELECT
    CAST(ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS INT) AS BackformId,
    JSON_VALUE(data.value, '$.originFacilityCode') AS originFacilityCode,
    JSON_VALUE(data.value, '$.referralNumber') AS referralNumber,
    JSON_VALUE(data.value, '$.forwardCaseNumber') AS forwardCaseNumber,
    JSON_VALUE(data.value, '$.paperFormId') AS paperFormId,
    JSON_VALUE(data.value, '$.referringDoctorName') AS referringDoctorName,
    JSON_VALUE(data.value, '$.nationalIdNumber') AS nationalIdNumber,
    JSON_VALUE(data.value, '$.firstName') AS firstName,
    JSON_VALUE(data.value, '$.lastName') AS lastName,
    JSON_VALUE(data.value, '$.fathersName') AS fathersName,
    JSON_VALUE(data.value, '$.patientGender') AS patientGender,
    JSON_VALUE(data.value, '$.visibleDisability') AS visibleDisability,
    JSON_VALUE(data.value, '$.phoneNumber') AS phoneNumber,
    JSON_VALUE(data.value, '$.contactName') AS contactName,
    JSON_VALUE(data.value, '$.governorate') AS governorate,
    JSON_VALUE(data.value, '$.district') AS district,
    JSON_VALUE(data.value, '$.subdistrict') AS subdistrict,
    JSON_VALUE(data.value, '$.community') AS community,
    JSON_VALUE(data.value, '$.residentialStatus') AS residentialStatus,
    JSON_VALUE(data.value, '$.dateOfBirth') AS dateOfBirth,
    JSON_VALUE(data.value, '$.age') AS age,
    JSON_VALUE(data.value, '$.ageUnit') AS ageUnit,
    JSON_VALUE(data.value, '$.isUrgent') AS isUrgent,
    JSON_VALUE(data.value, '$.referralReason') AS referralReason,
    JSON_VALUE(data.value, '$.forwardDiagnosis') AS forwardDiagnosis,
    JSON_VALUE(data.value, '$.forwardDiagnosisICD10') AS forwardDiagnosisICD10,
    JSON_VALUE(data.value, '$.backDiagnosis') AS backDiagnosis,
    JSON_VALUE(data.value, '$.backdiagnosisICD10') AS backDiagnosisICD10,
    JSON_VALUE(data.value, '$.otherDiagnosisSupport') AS otherDiagnosisSupport,
    JSON_VALUE(data.value, '$.otherMedicalDevice') AS otherMedicalDevice,
    JSON_VALUE(data.value, '$.otherTreatmentOption') AS otherTreatmentOption,
    JSON_VALUE(data.value, '$.medicalHistory') AS medicalHistory,
    JSON_VALUE(data.value, '$.clinicalAndMedicalExamination') AS clinicalAndMedicalExamination,
    JSON_VALUE(data.value, '$.treatmentProvided') AS treatmentProvided,
    JSON_VALUE(data.value, '$.recommendations') AS recommendations,
    JSON_VALUE(data.value, '$.height') AS height,
    JSON_VALUE(data.value, '$.weight') AS weight,
    JSON_VALUE(data.value, '$.bloodPressure') AS bloodPressure,
    JSON_VALUE(data.value, '$.oxygen') AS oxygen,
    JSON_VALUE(data.value, '$.heartRate') AS heartRate,
    JSON_VALUE(data.value, '$.temperatureInCelsius') AS temperatureInCelsius,
    JSON_VALUE(data.value, '$.status') AS status,
    JSON_VALUE(data.value, '$.createdAt') AS createdAt,
    JSON_VALUE(data.value, '$.updatedAt') AS updatedAt,
	DATEADD(day, DATEDIFF(day, 0, JSON_VALUE(data.value, '$.createdAt')), 0) AS roundedCreatedDate
FROM extract.jsonExtract r
CROSS APPLY OPENJSON(r.jsonString, '$.data') AS data
WHERE
datasetName='Backform'